import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AccountRetrievalPart1(),
        ]),
      ),
    );
  }
}

class AccountRetrievalPart1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1024,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF4CA82)),
          child: Stack(
            children: [
              Positioned(
                left: 965,
                top: 771,
                child: Container(
                  width: 286,
                  height: 333,
                  child: Stack(children: [
                  ]),
                ),
              ),
              Positioned(
                left: 62,
                top: 216,
                child: Text(
                  'Get back into your account',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 40,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 276,
                child: Text(
                  'Who are you?',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 32,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 61,
                top: 672,
                child: Container(
                  width: 542,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 747,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Enter the characters in the picture or the words in the audio. ',
                        style: TextStyle(
                          color: Color(0xFF630F12),
                          fontSize: 20,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                          height: 0,
                        ),
                      ),
                      TextSpan(
                        text: '*',
                        style: TextStyle(
                          color: Color(0xFFC91A1A),
                          fontSize: 20,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 798,
                child: Container(
                  width: 255,
                  height: 64,
                  decoration: ShapeDecoration(
                    color: Color(0xFF630F12),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFFF4CA82)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 370,
                top: 798,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    width: 255,
                    height: 64,
                    decoration: ShapeDecoration(
                      color: Color(0xB2D7A11F),
                      shape: RoundedRectangleBorder(
                        side: BorderSide(width: 1, color: Color(0xFF630F12)),
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 805,
                child: Text(
                  'Next',
                  style: TextStyle(
                    color: Color(0xFFF4CA82),
                    fontSize: 40,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 440,
                top: 810,
                child: Text(
                  'Cancel',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 32,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: -14,
                top: -289,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 1718,
                    height: 428,
                    decoration: ShapeDecoration(
                      color: Color(0xFF630F12),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 110,
                child: Container(
                  width: 388,
                  height: 58,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/388x58"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 217,
                top: 875,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 766,
                    height: 679,
                    decoration: ShapeDecoration(
                      color: Color(0xFFF4CA82),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 540,
                top: 968,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 1164,
                    height: 469,
                    decoration: ShapeDecoration(
                      color: Color(0xFFCE3027),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 438,
                child: Container(
                  width: 542,
                  height: 49,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 340,
                child: Text(
                  'To recover your account, begin by entering your email or username and the characters in the picture or audio below.',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 390,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Email or Username:',
                        style: TextStyle(
                          color: Color(0xFF630F12),
                          fontSize: 20,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                          height: 0,
                        ),
                      ),
                      TextSpan(
                        text: ' *',
                        style: TextStyle(
                          color: Color(0xFFC91A1A),
                          fontSize: 20,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 510,
                child: Text(
                  'Example: user@cit.edu',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 1114,
                top: 605,
                child: Container(
                  width: 286,
                  height: 333,
                  child: Stack(children: [
                  ]),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}