import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Frame1(),
        ]),
      ),
    );
  }
}

class Frame1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1024,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF4CA82)),
          child: Stack(
            children: [
              Positioned(
                left: 951,
                top: -151,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 633,
                    height: 413,
                    decoration: ShapeDecoration(
                      color: Color(0xFFD7A11F),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 198,
                top: 426,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 575,
                    height: 660,
                    decoration: ShapeDecoration(
                      color: Color(0xCCD7A11F),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 816,
                top: 477,
                child: Container(
                  width: 523,
                  height: 47,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF630F12)),
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 816,
                top: 427,
                child: Text(
                  'Sign in',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 808,
                top: 733,
                child: Text(
                  'Can’t Access your Account?',
                  style: TextStyle(
                    color: Color(0xFFF8FBFF),
                    fontSize: 24,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 808,
                top: 695,
                child: Text(
                  'No Account?',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 24,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 973,
                top: 695,
                child: Text(
                  'Create one!',
                  style: TextStyle(
                    color: Color(0xFFFEFEFB),
                    fontSize: 24,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 709,
                top: 69,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 406,
                    height: 374,
                    decoration: ShapeDecoration(
                      color: Color(0xFFF4CA82),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 829,
                top: -15,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 309,
                    height: 141,
                    decoration: ShapeDecoration(
                      color: Color(0xFFDFDDDE),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 825,
                top: -79,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 340,
                    height: 106,
                    decoration: ShapeDecoration(
                      color: Color(0xFFDFDDDE),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1276,
                top: 27,
                child: Container(
                  width: 156,
                  height: 199,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/156x199"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 829,
                top: 73,
                child: Text(
                  'Continue to ',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 64,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 773,
                top: 335,
                child: SizedBox(
                  width: 675,
                  height: 46,
                  child: Text(
                    'Hello there! Get ready to dive into the excitement!',
                    style: TextStyle(
                      color: Color(0xFF630F12),
                      fontSize: 25,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1118,
                top: 800,
                child: Container(
                  width: 236,
                  height: 62,
                  decoration: ShapeDecoration(
                    color: Color(0xFF630F12),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 816,
                top: 535,
                child: Text(
                  'Enter password',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 35,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 816,
                top: 580,
                child: Container(
                  width: 523,
                  height: 47,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF630F12)),
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 808,
                top: 771,
                child: Text(
                  'Forgot Password?',
                  style: TextStyle(
                    color: Color(0xFFF9FCFF),
                    fontSize: 24,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 1163,
                top: 806,
                child: Text(
                  'Sign In',
                  style: TextStyle(
                    color: Color(0xFFF4CA82),
                    fontSize: 40,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 816,
                top: 651,
                child: Container(
                  width: 27,
                  height: 24,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF630F12)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 856,
                top: 648,
                child: SizedBox(
                  width: 279,
                  height: 38,
                  child: Text(
                    'Keep me signed in',
                    style: TextStyle(
                      color: Color(0xFF630F12),
                      fontSize: 28,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
