import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Verification(),
        ]),
      ),
    );
  }
}

class Verification extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1440,
          height: 1024,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFEFC47E)),
          child: Stack(
            children: [
              Positioned(
                left: 1081,
                top: -62,
                child: Opacity(
                  opacity: 0.90,
                  child: Container(
                    width: 448,
                    height: 433,
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(),
                    child: Stack(
                      children: [
                        Positioned(
                          left: -89,
                          top: -296,
                          child: Container(
                            width: 448,
                            height: 433,
                            padding: const EdgeInsets.only(
                              top: 119.98,
                              left: 134.59,
                              right: 136.27,
                              bottom: 120.58,
                            ),
                            clipBehavior: Clip.antiAlias,
                            decoration: BoxDecoration(),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                              
                              ],
                            ),
                          ),
                        ),
                        Positioned(
                          left: 56,
                          top: 36.08,
                          child: Container(
                            width: 336,
                            height: 360.83,
                            child: Stack(children: [
                            
                            ]),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 536,
                top: 898,
                child: Opacity(
                  opacity: 0.50,
                  child: Container(
                    width: 1313,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: Color(0xFF7D0303),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -203,
                top: -140,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 1313,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: Color(0xFF7D0303),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 331,
                top: 209,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 777,
                    height: 606,
                    decoration: ShapeDecoration(
                      color: Color(0xE57D0303),
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          strokeAlign: BorderSide.strokeAlignOutside,
                          color: Color(0xFF7D0303),
                        ),
                        borderRadius: BorderRadius.circular(30),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 407,
                top: 238,
                child: Text(
                  'Please verify your email!',
                  style: TextStyle(
                    color: Color(0xFFF4CA82),
                    fontSize: 50,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 518,
                top: 341,
                child: Text(
                  'You’re almost there! We sent an email to',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 458,
                top: 473,
                child: Text(
                  'Just click the button below to complete your signup.',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 487,
                top: 632,
                child: Text(
                  'Still didn’t receive the verification? No problem',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 445,
                top: 396,
                child: Container(
                  width: 550,
                  height: 46,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 653,
                top: 407,
                child: Text(
                  'omg@cit.edu',
                  style: TextStyle(
                    color: Color(0xFF630F12),
                    fontSize: 20,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 602,
                top: 528,
                child: Container(
                  width: 236,
                  height: 73,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE4B44D),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF7D0303)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 470,
                top: 687,
                child: Container(
                  width: 500,
                  height: 73,
                  decoration: ShapeDecoration(
                    color: Color(0xFF630F12),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF7D0303)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 680,
                top: 550,
                child: SizedBox(
                  width: 82,
                  height: 37,
                  child: Text(
                    'Done',
                    style: TextStyle(
                      color: Color(0xFF7D0303),
                      fontSize: 27,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 536,
                top: 706,
                child: SizedBox(
                  width: 368,
                  height: 36,
                  child: Text(
                    'Resend Verification Email',
                    style: TextStyle(
                      color: Color(0xFFF4CA82),
                      fontSize: 27,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1193,
                top: 40,
                child: Container(
                  width: 223,
                  height: 228,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/223x228"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1137,
                top: 209,
                child: Container(
                  width: 448,
                  height: 433,
                  padding: const EdgeInsets.symmetric(horizontal: 56, vertical: 36.08),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Opacity(
                        opacity: 0.70,
                        child: Container(
                          width: 336,
                          height: 360.83,
                          child: Stack(children: [
                          
                          ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -7,
                top: 706,
                child: Opacity(
                  opacity: 0.70,
                  child: Container(
                    width: 338,
                    height: 321,
                    padding: const EdgeInsets.only(
                      top: 26.75,
                      left: 28.17,
                      right: 28.16,
                      bottom: 26.75,
                    ),
                    clipBehavior: Clip.antiAlias,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment(0.00, -1.00),
                        end: Alignment(0, 1),
                        colors: [Color(0xFFE09C2D), Color(0x00F3C881)],
                      ),
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Container(
                          width: 281.67,
                          height: 267.50,
                          child: Stack(children: [
                          
                          ]),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 17,
                child: Container(
                  width: 102,
                  height: 83,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(children: [
                  
                  ]),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}